# Generated by Django 4.1 on 2023-02-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='image',
        ),
    ]
