# Generated by Django 4.1 on 2023-02-07 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_alter_kebele_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='residents/'),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
