# Generated by Django 4.1 on 2023-02-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_resident_profile_image_alter_kebele_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebele',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
