# Generated by Django 4.1 on 2023-02-07 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_alter_kebele_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebele',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
