# Generated by Django 4.1 on 2023-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_alter_kebele_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reported_birth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(max_length=200, null=True)),
                ('birth_place', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Faleme', 'Famele'), ('other', 'other')], max_length=50)),
                ('birth_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='reported_death',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('Death_date', models.DateField(max_length=200, null=True)),
                ('cause_of_death', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('death_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='reported_divorces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name_hus', models.CharField(max_length=50, null=True)),
                ('last_name_hus', models.CharField(max_length=50, null=True)),
                ('first_name_wife', models.CharField(max_length=50, null=True)),
                ('last_name_wife', models.CharField(max_length=50, null=True)),
                ('divorce_date', models.DateField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('divorce_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='reported_marriages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name_hus', models.CharField(max_length=50, null=True)),
                ('last_name_hus', models.CharField(max_length=50, null=True)),
                ('first_name_wife', models.CharField(max_length=50, null=True)),
                ('last_name_wife', models.CharField(max_length=50, null=True)),
                ('marriage_date', models.DateField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marriage_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='resident',
            name='Death_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='birth_place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='cause_of_death',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='current_status',
            field=models.BooleanField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='Birth_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='marital_status',
            field=models.BooleanField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='single', max_length=20),
        ),
    ]
