# Generated by Django 4.1 on 2023-02-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_reported_birth_reported_death_reported_divorces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Resident_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
