# Generated by Django 4.1 on 2023-02-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_alter_resident_resident_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='Birth_date',
        ),
        migrations.AlterField(
            model_name='resident',
            name='Resident_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
