# Generated by Django 4.1 on 2023-02-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_resident_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_birth',
            name='for_kebele',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
        migrations.AddField(
            model_name='reported_death',
            name='for_kebele',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
        migrations.AddField(
            model_name='reported_divorces',
            name='for_kebele',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
        migrations.AddField(
            model_name='reported_marriages',
            name='for_kebele',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
    ]
