# Generated by Django 4.1 on 2023-02-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_reported_birth_for_kebele_reported_death_for_kebele_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reported_death',
            old_name='Death_date',
            new_name='death_date',
        ),
    ]
