# Generated by Django 4.1 on 2023-02-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_rename_death_date_reported_death_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
