# Generated by Django 4.1 on 2023-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_alter_resident_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='Death_date',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='No_of_Divorse',
            new_name='no_of_divorce',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='No_of_marrige',
            new_name='no_of_marriage',
        ),
        migrations.AlterField(
            model_name='reported_birth',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='current_status',
            field=models.BooleanField(blank=True, choices=[('alive', 'alive'), ('dead', 'dead')], default='alive', null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
