# Generated by Django 4.1 on 2023-02-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_rename_death_date_resident_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Kebele_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='current_status',
            field=models.CharField(blank=True, choices=[('alive', 'alive'), ('dead', 'dead')], default='alive', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='single', max_length=20),
        ),
    ]
