# Generated by Django 4.1 on 2023-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_resident_kebele_name_alter_resident_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='death_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
