# Generated by Django 4.1 on 2023-02-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_resident_kebele_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={},
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
