# Generated by Django 4.1 on 2023-02-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_alter_resident_cause_of_death_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='Kebele_name',
            new_name='kebele_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Faleme', 'Female'), ('other', 'other')], default='Male', max_length=50),
        ),
    ]
