# Generated by Django 4.1.4 on 2023-02-09 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_alter_resident_current_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.RenameField(
            model_name='reported_death',
            old_name='death_date',
            new_name='Death_date',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='death_date',
            new_name='Death_date',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='no_of_divorce',
            new_name='No_of_divorce',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='no_of_marriage',
            new_name='No_of_marriage',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='kebele_name',
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='divorce_date',
            field=models.DateField(max_length=200, null=True, verbose_name='Divorce Date'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='divorce_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Divorce Proof'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='first_name_hus',
            field=models.CharField(max_length=50, null=True, verbose_name='Husband First Name'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='first_name_wife',
            field=models.CharField(max_length=50, null=True, verbose_name='Wife First Name'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='for_kebele',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele', verbose_name='For Kebele'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='last_name_hus',
            field=models.CharField(max_length=50, null=True, verbose_name='Husband Last Name'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='last_name_wife',
            field=models.CharField(max_length=50, null=True, verbose_name='Wife Last Name'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='first_name_hus',
            field=models.CharField(max_length=50, null=True, verbose_name='Husband First Name'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='first_name_wife',
            field=models.CharField(max_length=50, null=True, verbose_name='Wife First Name'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='for_kebele',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele', verbose_name='For Kebele'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='last_name_hus',
            field=models.CharField(max_length=50, null=True, verbose_name='Husband Last Name'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='last_name_wife',
            field=models.CharField(max_length=50, null=True, verbose_name='Wife Last Name'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='marriage_date',
            field=models.DateTimeField(max_length=200, null=True, verbose_name='Marriage Date'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='marriage_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Marriage Proof Photo'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='current_status',
            field=models.CharField(blank=True, default='alive', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='single', max_length=20),
        ),
    ]
