# Generated by Django 4.1 on 2023-02-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_alter_resident_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_birth',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reported_birth',
            name='birth_proof',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='reported_death',
            name='death_proof',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='reported_divorces',
            name='divorce_proof',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='reported_marriages',
            name='marriage_proof',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='proofs/'),
        ),
    ]
